-- Insert trail routes data for all 15 hiking spots
-- This script inserts 75 trail routes (5 per spot) into the hiking_spot_routes table

-- Mount Babag
INSERT INTO hiking_spot_routes (hiking_spot_id, route_name, difficulty, distance, elevation_gain, estimated_duration, route_features, route_description) VALUES
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Babag' LIMIT 1), 'Babag Ridge Easy Trail', 'Easy', 2.5, 180, 90, 'Gentle slopes through pine forests, perfect for beginners, scenic viewpoints of Cebu City, well-marked trail with rest areas', 'The primary route to Mount Babag summit with well-marked trails and scenic viewpoints.'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Babag' LIMIT 1), 'Babag Summit Trail', 'Moderate', 4.8, 680, 210, 'Challenging ascent, summit views, rock formations', 'Challenging ascent to the summit with rock formations and panoramic views'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Babag' LIMIT 1), 'Babag Nature Trail', 'Easy', 2.1, 280, 90, 'Family-friendly, nature observation, bird watching', 'Family-friendly trail perfect for nature observation and bird watching'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Babag' LIMIT 1), 'Babag Sunrise Trail', 'Moderate', 3.8, 520, 168, 'Best sunrise viewpoint, early morning hike, photography', 'Best sunrise viewpoint perfect for early morning photography'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Babag' LIMIT 1), 'Babag Adventure Trail', 'Hard', 5.5, 750, 240, 'Technical sections, rope climbing, experienced hikers only', 'Technical trail with rope climbing sections for experienced hikers only');

-- Mount Kan-irag / Sirao Peak
INSERT INTO hiking_spot_routes (hiking_spot_id, route_name, difficulty, distance, elevation_gain, estimated_duration, route_features, route_description) VALUES
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Kan-irag / Sirao Peak' LIMIT 1), 'Sirao Flower Garden Trail', 'Easy', 2.0, 120, 60, 'Gentle walk through colorful flower gardens, cool mountain air, perfect for families, celosia and other seasonal blooms', 'Gentle walk through colorful flower gardens, cool mountain air, perfect for families, celosia and other seasonal blooms'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Kan-irag / Sirao Peak' LIMIT 1), 'Kan-irag Nature Walk', 'Moderate', 3.5, 250, 120, 'Moderate climb through pine and eucalyptus forests, bird watching opportunities, scenic overlooks of Temple of Leah', 'Moderate climb through pine and eucalyptus forests, bird watching opportunities, scenic overlooks of Temple of Leah'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Kan-irag / Sirao Peak' LIMIT 1), 'Sirao Peak Summit', 'Moderate', 4.0, 310, 150, 'Direct route to the highest point, cool climate vegetation, stunning views of Cebu City and Bohol strait', 'Direct route to the highest point, cool climate vegetation, stunning views of Cebu City and Bohol strait'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Kan-irag / Sirao Peak' LIMIT 1), 'Kan-irag Ridge Challenge', 'Hard', 5.8, 420, 210, 'Challenging ridge walk with steep ascents, diverse flora including native orchids, multiple scenic viewpoints', 'Challenging ridge walk with steep ascents, diverse flora including native orchids, multiple scenic viewpoints'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Kan-irag / Sirao Peak' LIMIT 1), 'Sirao Extreme Loop', 'Expert', 7.5, 520, 270, 'Technical loop trail with rock climbing sections, pristine forest areas, expert navigation required, remote wilderness experience', 'Technical loop trail with rock climbing sections, pristine forest areas, expert navigation required, remote wilderness experience');

-- Mount Naupa
INSERT INTO hiking_spot_routes (hiking_spot_id, route_name, difficulty, distance, elevation_gain, estimated_duration, route_features, route_description) VALUES
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Naupa' LIMIT 1), 'Naupa Base Trail', 'Easy', 2.8, 200, 90, 'Accessible trail through agricultural areas, local community interaction, gentle slopes with fruit trees and vegetable gardens', 'Accessible trail through agricultural areas, local community interaction, gentle slopes with fruit trees and vegetable gardens'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Naupa' LIMIT 1), 'Naupa Forest Path', 'Moderate', 4.5, 340, 150, 'Moderate climb through secondary forest, diverse bird species, natural springs along the trail, shaded canopy walk', 'Moderate climb through secondary forest, diverse bird species, natural springs along the trail, shaded canopy walk'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Naupa' LIMIT 1), 'Naupa Summit Route', 'Moderate', 5.2, 380, 180, 'Traditional summit approach, mixed terrain with river crossings, panoramic views of Naga City and surrounding valleys', 'Traditional summit approach, mixed terrain with river crossings, panoramic views of Naga City and surrounding valleys'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Naupa' LIMIT 1), 'Naupa Wilderness Trek', 'Hard', 6.8, 480, 240, 'Challenging wilderness route, dense forest sections, wildlife spotting opportunities, steep rocky ascents', 'Challenging wilderness route, dense forest sections, wildlife spotting opportunities, steep rocky ascents'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Naupa' LIMIT 1), 'Naupa Technical Ascent', 'Expert', 8.0, 600, 300, 'Expert-level technical climbing, rope work required, pristine old-growth forest, spectacular summit views', 'Expert-level technical climbing, rope work required, pristine old-growth forest, spectacular summit views');

-- Mount Manunggal
INSERT INTO hiking_spot_routes (hiking_spot_id, route_name, difficulty, distance, elevation_gain, estimated_duration, route_features, route_description) VALUES
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Manunggal' LIMIT 1), 'Manunggal Memorial Trail', 'Easy', 3.0, 220, 90, 'Historical trail to crash site memorial, educational markers, gentle slopes through grasslands, cultural significance', 'Historical trail to crash site memorial, educational markers, gentle slopes through grasslands, cultural significance'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Manunggal' LIMIT 1), 'Manunggal Heritage Path', 'Moderate', 4.8, 360, 150, 'Moderate climb with historical significance, monument visits, scenic views of western Cebu coast, well-maintained trail', 'Moderate climb with historical significance, monument visits, scenic views of western Cebu coast, well-maintained trail'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Manunggal' LIMIT 1), 'Manunggal Summit Classic', 'Moderate', 5.5, 420, 180, 'Traditional route to the summit, mixed forest and grassland terrain, panoramic coastal views, memorial site visit', 'Traditional route to the summit, mixed forest and grassland terrain, panoramic coastal views, memorial site visit'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Manunggal' LIMIT 1), 'Manunggal Ridge Adventure', 'Hard', 7.2, 540, 240, 'Challenging ridge traverse, steep ascents through dense forest, multiple viewpoints, technical rock sections', 'Challenging ridge traverse, steep ascents through dense forest, multiple viewpoints, technical rock sections'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Manunggal' LIMIT 1), 'Manunggal Extreme Challenge', 'Expert', 9.0, 680, 330, 'Expert-level mountain traverse, exposed ridge walking, rope-assisted sections, breathtaking summit panorama', 'Expert-level mountain traverse, exposed ridge walking, rope-assisted sections, breathtaking summit panorama');

-- Mount Mago
INSERT INTO hiking_spot_routes (hiking_spot_id, route_name, difficulty, distance, elevation_gain, estimated_duration, route_features, route_description) VALUES
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Mago' LIMIT 1), 'Mago Foothills Trail', 'Easy', 2.5, 180, 90, 'Gentle introduction to mountain hiking, agricultural landscapes, local community trails, fruit orchards and vegetable farms', 'Gentle introduction to mountain hiking, agricultural landscapes, local community trails, fruit orchards and vegetable farms'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Mago' LIMIT 1), 'Mago Forest Route', 'Moderate', 4.0, 320, 150, 'Moderate forest climb, diverse tropical vegetation, natural water sources, bird watching opportunities', 'Moderate forest climb, diverse tropical vegetation, natural water sources, bird watching opportunities'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Mago' LIMIT 1), 'Mago Summit Trail', 'Moderate', 5.0, 400, 180, 'Direct summit approach, mixed terrain with rocky outcrops, panoramic views of Carmen and Danao areas', 'Direct summit approach, mixed terrain with rocky outcrops, panoramic views of Carmen and Danao areas'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Mago' LIMIT 1), 'Mago Technical Route', 'Hard', 6.5, 520, 240, 'Challenging technical climbing, steep rock faces, dense jungle sections, advanced navigation skills required', 'Challenging technical climbing, steep rock faces, dense jungle sections, advanced navigation skills required'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Mago' LIMIT 1), 'Mago Extreme Traverse', 'Expert', 8.5, 650, 300, 'Expert-level mountain traverse, exposed cliff sections, pristine wilderness, spectacular 360-degree views', 'Expert-level mountain traverse, exposed cliff sections, pristine wilderness, spectacular 360-degree views');

-- Mount Kapayas
INSERT INTO hiking_spot_routes (hiking_spot_id, route_name, difficulty, distance, elevation_gain, estimated_duration, route_features, route_description) VALUES
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Kapayas' LIMIT 1), 'Kapayas Coastal Trail', 'Easy', 2.8, 160, 90, 'Easy coastal mountain trail, sea breeze cooling, views of Camotes Sea, gentle slopes through coconut groves', 'Easy coastal mountain trail, sea breeze cooling, views of Camotes Sea, gentle slopes through coconut groves'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Kapayas' LIMIT 1), 'Kapayas Nature Walk', 'Moderate', 4.2, 280, 120, 'Moderate climb through tropical forest, diverse plant species, natural springs, coastal and mountain views', 'Moderate climb through tropical forest, diverse plant species, natural springs, coastal and mountain views'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Kapayas' LIMIT 1), 'Kapayas Summit Route', 'Moderate', 5.0, 350, 150, 'Traditional summit trail, mixed forest and grassland, panoramic views of northern Cebu coast and islands', 'Traditional summit trail, mixed forest and grassland, panoramic views of northern Cebu coast and islands'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Kapayas' LIMIT 1), 'Kapayas Ridge Challenge', 'Hard', 6.8, 460, 210, 'Challenging ridge walk, steep ascents, dense forest sections, technical rock scrambling, remote wilderness', 'Challenging ridge walk, steep ascents, dense forest sections, technical rock scrambling, remote wilderness'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Kapayas' LIMIT 1), 'Kapayas Extreme Circuit', 'Expert', 8.0, 580, 270, 'Expert-level circuit trail, exposed ridge sections, rope work required, pristine forest, spectacular summit views', 'Expert-level circuit trail, exposed ridge sections, rope work required, pristine forest, spectacular summit views');

-- Mount Lantoy
INSERT INTO hiking_spot_routes (hiking_spot_id, route_name, difficulty, distance, elevation_gain, estimated_duration, route_features, route_description) VALUES
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Lantoy' LIMIT 1), 'Lantoy Beach Trail', 'Easy', 2.2, 140, 60, 'Easy beach access trail, coastal scenery, gentle slopes, perfect for families and beginners', 'Easy beach access trail, coastal scenery, gentle slopes, perfect for families and beginners'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Lantoy' LIMIT 1), 'Lantoy Forest Path', 'Moderate', 4.5, 320, 150, 'Moderate climb through coastal forest, diverse marine and terrestrial ecosystems, scenic ocean views', 'Moderate climb through coastal forest, diverse marine and terrestrial ecosystems, scenic ocean views'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Lantoy' LIMIT 1), 'Lantoy Summit Classic', 'Moderate', 5.8, 420, 180, 'Traditional summit route, mixed coastal and mountain terrain, panoramic sea and island views', 'Traditional summit route, mixed coastal and mountain terrain, panoramic sea and island views'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Lantoy' LIMIT 1), 'Lantoy Ridge Adventure', 'Hard', 7.5, 550, 240, 'Challenging ridge walk, steep coastal cliffs, technical sections, spectacular ocean panoramas', 'Challenging ridge walk, steep coastal cliffs, technical sections, spectacular ocean panoramas'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Lantoy' LIMIT 1), 'Lantoy Extreme Traverse', 'Expert', 9.2, 680, 300, 'Expert-level coastal mountain traverse, exposed cliff sections, pristine wilderness areas', 'Expert-level coastal mountain traverse, exposed cliff sections, pristine wilderness areas');

-- Mount Kalbasaan
INSERT INTO hiking_spot_routes (hiking_spot_id, route_name, difficulty, distance, elevation_gain, estimated_duration, route_features, route_description) VALUES
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Kalbasaan' LIMIT 1), 'Kalbasaan Family Trail', 'Easy', 1.8, 120, 60, 'Perfect family-friendly trail, gentle slopes, well-maintained paths, picnic areas, city views', 'Perfect family-friendly trail, gentle slopes, well-maintained paths, picnic areas, city views'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Kalbasaan' LIMIT 1), 'Kalbasaan Nature Walk', 'Easy', 3.2, 180, 90, 'Easy nature walk, diverse plant species, bird watching, educational trail markers', 'Easy nature walk, diverse plant species, bird watching, educational trail markers'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Kalbasaan' LIMIT 1), 'Kalbasaan Summit Easy', 'Moderate', 4.5, 280, 120, 'Easy summit approach, gradual climb, panoramic city and mountain views, well-marked trail', 'Easy summit approach, gradual climb, panoramic city and mountain views, well-marked trail'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Kalbasaan' LIMIT 1), 'Kalbasaan Extended Loop', 'Moderate', 6.2, 380, 180, 'Extended loop trail, mixed terrain, additional viewpoints, longer hiking experience', 'Extended loop trail, mixed terrain, additional viewpoints, longer hiking experience'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Kalbasaan' LIMIT 1), 'Kalbasaan Challenge Route', 'Hard', 7.8, 480, 240, 'More challenging terrain, steep sections, technical rock scrambling, rewarding summit views', 'More challenging terrain, steep sections, technical rock scrambling, rewarding summit views');

-- Mount Mauyog
INSERT INTO hiking_spot_routes (hiking_spot_id, route_name, difficulty, distance, elevation_gain, estimated_duration, route_features, route_description) VALUES
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Mauyog' LIMIT 1), 'Mauyog Foothills Path', 'Easy', 2.5, 150, 90, 'Easy foothills approach, agricultural areas, local community interaction, gentle terrain', 'Easy foothills approach, agricultural areas, local community interaction, gentle terrain'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Mauyog' LIMIT 1), 'Mauyog Forest Trail', 'Moderate', 4.8, 320, 150, 'Moderate forest climb, diverse vegetation, natural water sources, bird watching opportunities', 'Moderate forest climb, diverse vegetation, natural water sources, bird watching opportunities'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Mauyog' LIMIT 1), 'Mauyog Summit Route', 'Moderate', 6.2, 420, 210, 'Traditional summit approach, mixed terrain, panoramic mountain and valley views', 'Traditional summit approach, mixed terrain, panoramic mountain and valley views'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Mauyog' LIMIT 1), 'Mauyog Ridge Challenge', 'Hard', 8.0, 550, 270, 'Challenging ridge walk, steep ascents, technical sections, spectacular mountain panoramas', 'Challenging ridge walk, steep ascents, technical sections, spectacular mountain panoramas'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Mauyog' LIMIT 1), 'Mauyog Extreme Traverse', 'Expert', 10.0, 680, 360, 'Expert-level mountain traverse, exposed ridge sections, pristine wilderness experience', 'Expert-level mountain traverse, exposed ridge sections, pristine wilderness experience');

-- Mount Lanaya
INSERT INTO hiking_spot_routes (hiking_spot_id, route_name, difficulty, distance, elevation_gain, estimated_duration, route_features, route_description) VALUES
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Lanaya' LIMIT 1), 'Lanaya Waterfall Trail', 'Moderate', 4.5, 280, 150, 'Trail to beautiful waterfall, swimming opportunities, lush vegetation, refreshing water features', 'Trail to beautiful waterfall, swimming opportunities, lush vegetation, refreshing water features'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Lanaya' LIMIT 1), 'Lanaya Forest Path', 'Moderate', 6.2, 380, 210, 'Forest trail with river crossings, diverse ecosystems, natural pools, scenic canyon views', 'Forest trail with river crossings, diverse ecosystems, natural pools, scenic canyon views'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Lanaya' LIMIT 1), 'Lanaya Summit Classic', 'Hard', 8.5, 520, 270, 'Challenging summit approach, steep terrain, waterfall viewpoints, panoramic mountain views', 'Challenging summit approach, steep terrain, waterfall viewpoints, panoramic mountain views'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Lanaya' LIMIT 1), 'Lanaya Extreme Loop', 'Expert', 12.0, 750, 390, 'Expert-level loop trail, technical climbing, pristine forest, spectacular waterfall and summit views', 'Expert-level loop trail, technical climbing, pristine forest, spectacular waterfall and summit views');

-- Mount Hambubuyog
INSERT INTO hiking_spot_routes (hiking_spot_id, route_name, difficulty, distance, elevation_gain, estimated_duration, route_features, route_description) VALUES
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Hambubuyog' LIMIT 1), 'Hambubuyog Coastal Trail', 'Moderate', 5.2, 350, 180, 'Coastal mountain trail, sea views, diverse marine life, challenging terrain with ocean breezes', 'Coastal mountain trail, sea views, diverse marine life, challenging terrain with ocean breezes'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Hambubuyog' LIMIT 1), 'Hambubuyog Summit Route', 'Hard', 7.8, 520, 270, 'Steep summit approach, technical rock sections, panoramic sea and island views', 'Steep summit approach, technical rock sections, panoramic sea and island views'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Hambubuyog' LIMIT 1), 'Hambubuyog Extreme Challenge', 'Expert', 10.5, 720, 360, 'Expert-level coastal traverse, exposed cliff sections, pristine wilderness, breathtaking ocean panoramas', 'Expert-level coastal traverse, exposed cliff sections, pristine wilderness, breathtaking ocean panoramas');

-- Osmeña Peak
INSERT INTO hiking_spot_routes (hiking_spot_id, route_name, difficulty, distance, elevation_gain, estimated_duration, route_features, route_description) VALUES
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Osmeña Peak' LIMIT 1), 'Osmeña Peak Easy Trail', 'Easy', 1.5, 100, 48, 'Short easy trail to highest peak in Cebu, 360-degree views, rolling hills landscape, perfect for all fitness levels', 'Short easy trail to highest peak in Cebu, 360-degree views, rolling hills landscape, perfect for all fitness levels'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Osmeña Peak' LIMIT 1), 'Osmeña Peak Classic Route', 'Easy', 2.5, 150, 72, 'Traditional approach to the peak, gentle slopes, panoramic views, well-maintained trail', 'Traditional approach to the peak, gentle slopes, panoramic views, well-maintained trail'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Osmeña Peak' LIMIT 1), 'Osmeña Peak Extended Walk', 'Moderate', 4.2, 280, 120, 'Extended trail through rolling hills, additional viewpoints, diverse grassland ecosystems', 'Extended trail through rolling hills, additional viewpoints, diverse grassland ecosystems'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Osmeña Peak' LIMIT 1), 'Osmeña Peak Challenge Loop', 'Moderate', 6.5, 380, 180, 'Loop trail around the peak area, varied terrain, multiple scenic viewpoints', 'Loop trail around the peak area, varied terrain, multiple scenic viewpoints'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Osmeña Peak' LIMIT 1), 'Osmeña Peak Extreme Traverse', 'Hard', 8.5, 480, 240, 'Challenging traverse of the entire ridge system, technical sections, spectacular panoramic views', 'Challenging traverse of the entire ridge system, technical sections, spectacular panoramic views');

-- Casino Peak
INSERT INTO hiking_spot_routes (hiking_spot_id, route_name, difficulty, distance, elevation_gain, estimated_duration, route_features, route_description) VALUES
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Casino Peak' LIMIT 1), 'Casino Peak Easy Access', 'Easy', 2.0, 120, 60, 'Easy access trail, less crowded alternative to Osmeña, similar views, gentler approach', 'Easy access trail, less crowded alternative to Osmeña, similar views, gentler approach'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Casino Peak' LIMIT 1), 'Casino Peak Nature Trail', 'Moderate', 3.8, 250, 120, 'Nature-focused trail, diverse plant species, bird watching, peaceful hiking experience', 'Nature-focused trail, diverse plant species, bird watching, peaceful hiking experience'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Casino Peak' LIMIT 1), 'Casino Peak Summit Route', 'Moderate', 4.5, 320, 150, 'Direct summit approach, panoramic views, well-marked trail, alternative to crowded Osmeña', 'Direct summit approach, panoramic views, well-marked trail, alternative to crowded Osmeña'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Casino Peak' LIMIT 1), 'Casino Peak Extended Loop', 'Hard', 6.2, 420, 210, 'Extended loop trail, additional viewpoints, varied terrain, longer hiking experience', 'Extended loop trail, additional viewpoints, varied terrain, longer hiking experience'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Casino Peak' LIMIT 1), 'Casino Peak Technical Challenge', 'Expert', 7.8, 520, 270, 'Technical trail with challenging sections, expert navigation, pristine wilderness areas', 'Technical trail with challenging sections, expert navigation, pristine wilderness areas');

-- Budlaan Falls
INSERT INTO hiking_spot_routes (hiking_spot_id, route_name, difficulty, distance, elevation_gain, estimated_duration, route_features, route_description) VALUES
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Budlaan Falls' LIMIT 1), 'Budlaan Falls Easy Trail', 'Easy', 3.5, 220, 120, 'Easy approach to beautiful waterfall, swimming opportunities, lush vegetation, family-friendly', 'Easy approach to beautiful waterfall, swimming opportunities, lush vegetation, family-friendly'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Budlaan Falls' LIMIT 1), 'Budlaan Falls Nature Path', 'Moderate', 5.2, 320, 180, 'Nature trail to waterfall, diverse plant species, natural pools, scenic canyon views', 'Nature trail to waterfall, diverse plant species, natural pools, scenic canyon views'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Budlaan Falls' LIMIT 1), 'Budlaan Falls Adventure Route', 'Hard', 7.8, 450, 270, 'Challenging waterfall route, river crossings, technical sections, pristine forest areas', 'Challenging waterfall route, river crossings, technical sections, pristine forest areas'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Budlaan Falls' LIMIT 1), 'Budlaan Falls Extreme Trek', 'Expert', 10.2, 580, 360, 'Expert-level waterfall trek, technical climbing, remote wilderness, spectacular water features', 'Expert-level waterfall trek, technical climbing, remote wilderness, spectacular water features');

-- Mount Kalawisan (Kanlaas Ridge)
INSERT INTO hiking_spot_routes (hiking_spot_id, route_name, difficulty, distance, elevation_gain, estimated_duration, route_features, route_description) VALUES
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Kalawisan (Kanlaas Ridge)' LIMIT 1), 'Kalawisan Ridge Easy Walk', 'Easy', 3.2, 180, 90, 'Easy ridge walk, panoramic northern Cebu views, grassland terrain, perfect for beginners', 'Easy ridge walk, panoramic northern Cebu views, grassland terrain, perfect for beginners'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Kalawisan (Kanlaas Ridge)' LIMIT 1), 'Kalawisan Nature Trail', 'Moderate', 5.5, 320, 150, 'Nature-focused trail, diverse grassland species, bird watching, scenic ridge views', 'Nature-focused trail, diverse grassland species, bird watching, scenic ridge views'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Kalawisan (Kanlaas Ridge)' LIMIT 1), 'Kalawisan Summit Route', 'Moderate', 7.2, 420, 210, 'Traditional summit approach, mixed terrain, panoramic northern Cebu and island views', 'Traditional summit approach, mixed terrain, panoramic northern Cebu and island views'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Kalawisan (Kanlaas Ridge)' LIMIT 1), 'Kalawisan Ridge Challenge', 'Hard', 9.5, 580, 270, 'Challenging ridge traverse, steep sections, technical terrain, spectacular panoramic views', 'Challenging ridge traverse, steep sections, technical terrain, spectacular panoramic views'),
((SELECT hiking_spot_id FROM hiking_spots WHERE name = 'Mount Kalawisan (Kanlaas Ridge)' LIMIT 1), 'Kalawisan Extreme Loop', 'Expert', 12.0, 720, 360, 'Expert-level ridge loop, exposed sections, pristine grassland wilderness, breathtaking summit views', 'Expert-level ridge loop, exposed sections, pristine grassland wilderness, breathtaking summit views');

-- Trail routes data insertion completed successfully!
-- All 15 hiking spots with 5 routes each (75 total routes) have been inserted into the hiking_spot_routes table.
