-- Friend requests table and RLS
create table if not exists public.friend_requests (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references auth.users(id) on delete cascade,
  receiver_id uuid not null references auth.users(id) on delete cascade,
  status text check (status in ('pending', 'accepted', 'declined')) default 'pending',
  created_at timestamptz default now()
);

alter table public.friend_requests enable row level security;

create policy if not exists "Friend requests are viewable by involved users"
  on public.friend_requests
  for select
  to authenticated
  using (auth.uid() = sender_id or auth.uid() = receiver_id);

create policy if not exists "Users can create their own friend requests"
  on public.friend_requests
  for insert
  to authenticated
  with check (auth.uid() = sender_id);

create policy if not exists "Recipient can accept or decline request"
  on public.friend_requests
  for update
  to authenticated
  using (auth.uid() = receiver_id)
  with check (auth.uid() = receiver_id);

create policy if not exists "Either user can delete friendship"
  on public.friend_requests
  for delete
  to authenticated
  using (auth.uid() = sender_id or auth.uid() = receiver_id);

create index if not exists idx_friend_requests_sender on public.friend_requests(sender_id);
create index if not exists idx_friend_requests_receiver on public.friend_requests(receiver_id);
